#include "levels.h"
#include "units.h"
#include "status.h"
#include "terrain.h"
#include "playerai.h"
#include "gamemusic.h"

#include <c64/vic.h>

AITask	aitasks1[] = {
	{AIS_IDLE + 0 * 8,  0,  0, 0},	// 0 
	{AIS_RUSH + 0 * 8,  3, 15, 0},	// 1 -> 0
	{AIS_RUSH + 7 * 8, 17,  9, 0},  // 2 -> 7
	{AIS_RUSH + 1 * 8, 11, 22, 0},  // 3 -> 1

	{AIS_IDLE + 5 * 8,  0,  0, 6},    // 4 -> 5
	{AIS_STROLL + 6 * 8, 20, 12, 0},  // 5 -> 6
	{AIS_STROLL + 0 * 8, 29, 16, 0},  // 6
	{AIS_STROLL + 0 * 8,  3, 15, 0},  // 7 -> 0
};

#define LEVEL_SEED(x) 							(x & 0xff), (x >> 8)
#define LEVEL_DAYS(d)							d
#define LEVEL_PATCH(x, y, d, s, t) 				x, y, d, (s | (t << 5))
#define LEVEL_PATCH_END							0xff
#define LEVEL_AI_TASK(com, next, x, y, day)		(com | (next << 3)), x, y, day
#define LEVAL_AI_END							0xff
#define LEVEL_UNIT(type, x, y, ai)				(type | (ai << 4)), x, y
#define LEVEL_UNIT_END							0xff


void level_setup_cmd(const char * cmd, bool terrain)
{
	GameDays = cmd[2];

	if (terrain)
	{
		terrain_build(cmd[0] + (cmd[1] << 8));
		cmd += 3;

		while (cmd[0] != LEVEL_PATCH_END)
		{
			char	dir = cmd[2];

			if (dir == 6)
				terrain_patch_circle(cmd[0], cmd[1], cmd[3] & 0x1f, cmd[3] >> 5);
			else
				terrain_patch(cmd[0], cmd[1], dir, cmd[3] & 0x1f, cmd[3] >> 5);

			cmd += 4;
		}
	}
	else
	{
		cmd += 3;
		while (cmd[0] != LEVEL_PATCH_END)
			cmd += 4;
	}
	cmd++;

	char	ntype[16];

	for(char i=0; i<16; i++)
		ntype[i] = 0;
	numUnits = 0;

	char	team = UNIT_TEAM_1;
	while (true)
	{
		char	unit = cmd[0] & 0x0f;
		bool	next = false;

		if (unit == UNIT_COMMAND_END)
		{
			unit = UNIT_COMMAND;
			next = true;
		}

		unit_add(unit | team, cmd[1], cmd[2], (cmd[0] >> 4 << 3) | ntype[unit]);
		cmd += 3;
		ntype[unit]++;

		if (next)
		{
			if (team == UNIT_TEAM_1)
			{
				for(char i=0; i<16; i++)
					ntype[i] = 0;
				team = UNIT_TEAM_2;
			}
			else
				break;
		}
	}

	AITasks	= (AITask *)cmd;
}

// OVERTURE
static const char level_data_overture[] = {
	LEVEL_SEED(36451),
	LEVEL_DAYS(8),

	LEVEL_PATCH_END,
	
	LEVEL_UNIT(UNIT_LIGHT_TANK, 14, 13, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 14, 14, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 15, 13, 0),

	LEVEL_UNIT(UNIT_INFANTRY, 14, 12, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 15, 11, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 13, 11, 0),

	LEVEL_UNIT(UNIT_LIGHT_TANK, 18, 10, 1),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 18, 14, 4),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 16, 16, 2),

	LEVEL_UNIT(UNIT_INFANTRY, 22, 12, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 24, 11, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 23, 11, 0),

	LEVEL_AI_TASK(AIS_IDLE,   0,  0,  0, 0),	// 0
	LEVEL_AI_TASK(AIS_RUSH,   0, 13, 14, 0),	// 1 -> 0
	LEVEL_AI_TASK(AIS_STROLL, 3, 23, 12, 0),	// 2 -> 3
	LEVEL_AI_TASK(AIS_HOLD,   0, 23, 12, 0),	// 3
	LEVEL_AI_TASK(AIS_HOLD,   1, 19, 13, 6)		// 4 -> 1
};

// ROAD TO
// VICTORY
static const char level_data_road_to_victory[] = {
	LEVEL_SEED(23893),
	LEVEL_DAYS(14),

	LEVEL_PATCH( 4, 16,  1, 13, GTERRAIN_ROAD),
	LEVEL_PATCH(17,  9,  2,  1, GTERRAIN_ROAD),
	LEVEL_PATCH(18, 10,  3,  1, GTERRAIN_ROAD),
	LEVEL_PATCH(18, 11,  2,  3, GTERRAIN_ROAD),
	LEVEL_PATCH(21, 12,  1,  5, GTERRAIN_ROAD),
	LEVEL_PATCH_END,


	LEVEL_UNIT(UNIT_HEAVY_TANK,  4, 15, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  4, 16, 0),

	LEVEL_UNIT(UNIT_LIGHT_TANK,  5, 14, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK,  5, 15, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK,  5, 16, 0),

	LEVEL_UNIT(UNIT_INFANTRY,  6, 13, 0),
	LEVEL_UNIT(UNIT_INFANTRY,  6, 14, 0),
	LEVEL_UNIT(UNIT_INFANTRY,  7, 13, 0),
	LEVEL_UNIT(UNIT_COMMAND_END,  3, 15, 0),

	LEVEL_UNIT(UNIT_HEAVY_TANK, 18, 11, 4),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 17, 13, 4),

	LEVEL_UNIT(UNIT_LIGHT_TANK, 13, 19, 3),
	LEVEL_UNIT(UNIT_LIGHT_TANK,  8, 10, 1),	
	LEVEL_UNIT(UNIT_LIGHT_TANK, 22, 14, 2),

	LEVEL_UNIT(UNIT_INFANTRY, 15,  9, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 29, 15, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 17, 10, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 29, 16, 0),

	LEVEL_AI_TASK(AIS_IDLE,   0,  0,  0, 0), // 0 
	LEVEL_AI_TASK(AIS_RUSH,   0,  3, 15, 0), // 1 -> 0
	LEVEL_AI_TASK(AIS_RUSH,   7, 17,  9, 0), // 2 -> 7
	LEVEL_AI_TASK(AIS_RUSH,   1, 11, 22, 0), // 3 -> 1

	LEVEL_AI_TASK(AIS_IDLE,   5,  0,  0, 6), // 4 -> 5
	LEVEL_AI_TASK(AIS_STROLL, 6, 20, 12, 0), // 5 -> 6
	LEVEL_AI_TASK(AIS_STROLL, 0, 29, 16, 0), // 6
	LEVEL_AI_TASK(AIS_STROLL, 0,  3, 15, 0), // 7 -> 0
};

// FIRE AND
// RETREAT
static const char level_data_fire_and_retreat[] = {
	LEVEL_SEED(9756),
	LEVEL_DAYS(15),

	LEVEL_PATCH( 7, 14,  1,  7, GTERRAIN_ROAD),
	LEVEL_PATCH(14, 12,  1,  1, GTERRAIN_ROAD),
	LEVEL_PATCH(21, 11,  1,  1, GTERRAIN_ROAD),
	LEVEL_PATCH_END,
	
	LEVEL_UNIT(UNIT_SCOUT_DRONE, 5, 13, 0),
	LEVEL_UNIT(UNIT_SCOUT_DRONE, 5, 14, 0),

	LEVEL_UNIT(UNIT_LIGHT_TANK,  8, 13, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK,  8, 14, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK,  8, 15, 0),

	LEVEL_UNIT(UNIT_HEAVY_TANK, 7, 13, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 7, 14, 0),

	LEVEL_UNIT(UNIT_ARTILLERY, 7, 11, 0),
	LEVEL_UNIT(UNIT_ARTILLERY, 8, 11, 0),

	LEVEL_UNIT(UNIT_INFANTRY,  7, 12, 0),
	LEVEL_UNIT(UNIT_INFANTRY,  6, 15, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 3, 13, 0),

	LEVEL_UNIT(UNIT_ARTILLERY, 19, 11, 3),
	LEVEL_UNIT(UNIT_ARTILLERY, 19, 14, 3),

	LEVEL_UNIT(UNIT_INFANTRY, 15, 12, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 15, 15, 0),

	LEVEL_UNIT(UNIT_LIGHT_TANK, 16, 11, 5),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 16, 12, 5),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 17, 11, 5),

	LEVEL_UNIT(UNIT_HEAVY_TANK, 18, 12, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 18, 13, 0),

	LEVEL_UNIT(UNIT_SCOUT_DRONE, 20,  9, 1),
	LEVEL_UNIT(UNIT_SCOUT_DRONE, 17, 18, 2),

	LEVEL_UNIT(UNIT_COMMAND_END, 28, 17, 0),

	LEVEL_AI_TASK(AIS_IDLE,   0,  0,  0, 0),	// 0
	LEVEL_AI_TASK(AIS_RUSH,   0,  6,  8, 0),	// 1 -> 0
	LEVEL_AI_TASK(AIS_STROLL, 0,  2, 18, 0),	// 2 -> 0
	LEVEL_AI_TASK(AIS_IDLE,   4,  0,  0, 8),	// 3 -> 4	
	LEVEL_AI_TASK(AIS_RUSH,   0, 16, 14, 0),	// 4 -> 0
	LEVEL_AI_TASK(AIS_RUSH,   6,  9, 10, 0),	// 5 -> 6
	LEVEL_AI_TASK(AIS_STROLL, 0,  3, 12, 0),	// 6 -> 0
};

// MOUNTAIN
// FORTRESS
static const char level_data_mountain_fortress[] = {
	LEVEL_SEED(23532),
	LEVEL_DAYS(20),

	LEVEL_PATCH(10, 18,  1,  3, GTERRAIN_ROAD),
	LEVEL_PATCH(12, 30,  0, 10, GTERRAIN_ROAD),
	LEVEL_PATCH(11, 20,  5,  2, GTERRAIN_ROAD),
	LEVEL_PATCH(10, 19,  0,  1, GTERRAIN_ROAD),
	LEVEL_PATCH_END,

	LEVEL_UNIT(UNIT_HOVERCRAFT,  1, 13, 0),
	LEVEL_UNIT(UNIT_HOVERCRAFT,  1, 14, 0),

	LEVEL_UNIT(UNIT_HOVERCRAFT,  9, 25, 0),
	LEVEL_UNIT(UNIT_HOVERCRAFT,  8, 26, 0),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 10, 25, 0),

	LEVEL_UNIT(UNIT_INFANTRY,  7, 18, 0),
	LEVEL_UNIT(UNIT_INFANTRY,  7, 19, 0),
	LEVEL_UNIT(UNIT_INFANTRY,  8, 19, 0),
	LEVEL_UNIT(UNIT_INFANTRY,  8, 20, 0),

	LEVEL_UNIT(UNIT_LIGHT_TANK,  9, 28, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 10, 29, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 11, 28, 0),

	LEVEL_UNIT(UNIT_SCOUT_DRONE,  2, 15, 0),
	LEVEL_UNIT(UNIT_SCOUT_DRONE, 15, 25, 0),

	LEVEL_UNIT(UNIT_COMMAND_END,  6, 29, 0),

	LEVEL_UNIT(UNIT_ARTILLERY, 18, 13, 0),
	LEVEL_UNIT(UNIT_ARTILLERY, 16, 11, 0),

	LEVEL_UNIT(UNIT_SCOUT_DRONE, 13, 15, 0),
	LEVEL_UNIT(UNIT_SCOUT_DRONE, 23, 20, 0),
	LEVEL_UNIT(UNIT_SCOUT_DRONE,  9,  6, 0),

	LEVEL_UNIT(UNIT_HEAVY_TANK, 12, 16, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 13, 16, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 18, 11, 0),

	LEVEL_AI_TASK(AIS_IDLE,   0,  0,  0, 0),	// 0
};

// VALKYRIE 
// RIDE
static const char level_data_valkyrie_ride[] = {
	LEVEL_SEED(39127),
	LEVEL_DAYS(20),

	LEVEL_PATCH(21,  9,  1,  2, GTERRAIN_BEACH),
	LEVEL_PATCH_END,

	LEVEL_UNIT(UNIT_CHOPPER,  9, 22, 0),
	LEVEL_UNIT(UNIT_CHOPPER,  9, 23, 0),
	LEVEL_UNIT(UNIT_CHOPPER,  8, 23, 0),
	LEVEL_UNIT(UNIT_CHOPPER, 10, 23, 0),
	LEVEL_UNIT(UNIT_CHOPPER,  8, 24, 0),
	LEVEL_UNIT(UNIT_CHOPPER, 10, 24, 0),

	LEVEL_UNIT(UNIT_HOVERCRAFT, 12, 24, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 12, 25, 0),

	LEVEL_UNIT(UNIT_SCOUT_DRONE, 21,  6, 0),
	LEVEL_UNIT(UNIT_SCOUT_DRONE, 28, 12, 0),
	LEVEL_UNIT(UNIT_SCOUT_DRONE, 21, 13, 0),

	LEVEL_UNIT(UNIT_AIR_DEFENCE, 24,  4, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 28,  5, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 23, 10, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 25, 12, 0),

	LEVEL_UNIT(UNIT_HEAVY_TANK, 29,  6, 2),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 29,  7, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 29,  8, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 30,  6, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 30,  9, 4),

	LEVEL_UNIT(UNIT_LIGHT_TANK, 19,  8, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 19,  9, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 19, 11, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 20, 11, 0),

	LEVEL_UNIT(UNIT_INFANTRY, 28,  6, 1),
	LEVEL_UNIT(UNIT_INFANTRY, 28,  8, 1),

	LEVEL_UNIT(UNIT_COMMAND_END, 30,  7, 0),

	LEVEL_AI_TASK(AIS_IDLE,   0,  0,  0,  0),	// 0
	LEVEL_AI_TASK(AIS_HOLD,   0, 28,  7,  0),	// 1
	LEVEL_AI_TASK(AIS_IDLE,   0,  0,  0, 10),	// 2 -> 3
	LEVEL_AI_TASK(AIS_STROLL, 0, 28,  5,  0),	// 3
	LEVEL_AI_TASK(AIS_IDLE,   0,  0,  0, 10),	// 4 -> 5
	LEVEL_AI_TASK(AIS_STROLL, 0, 29, 11,  0),	// 5
};

// SPECIAL FORCES
static const char level_data_special_forces[] = {
	LEVEL_SEED(22455),
	LEVEL_DAYS(24),

	LEVEL_PATCH( 9, 13,  2,  2, GTERRAIN_BEACH),
	LEVEL_PATCH(12, 10,  2,  4, GTERRAIN_MOUNTAIN),
	LEVEL_PATCH(15, 12,  2,  2, GTERRAIN_MOUNTAIN),
	LEVEL_PATCH( 8, 12,  3,  2, GTERRAIN_MOUNTAIN),
	LEVEL_PATCH(12,  8,  5,  3, GTERRAIN_FORREST),
	LEVEL_PATCH_END,

	LEVEL_UNIT(UNIT_INFANTRY, 24, 30, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 25, 29, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 18, 29, 0),

	LEVEL_UNIT(UNIT_CHOPPER, 21, 29, 0),
	LEVEL_UNIT(UNIT_CHOPPER, 23, 29, 0),
	LEVEL_UNIT(UNIT_CHOPPER, 22, 30, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 25, 30, 0),

	LEVEL_UNIT(UNIT_AIR_DEFENCE, 21, 21, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 22, 19, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 14, 18, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 20, 15, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 16, 12, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 13, 14, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 12, 11, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 15, 12, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 10, 12, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 11, 13, 0),

	LEVEL_UNIT(UNIT_ARTILLERY, 12, 22, 0),
	LEVEL_UNIT(UNIT_ARTILLERY, 12, 15, 0),
	LEVEL_UNIT(UNIT_ARTILLERY, 17, 10, 0),
	LEVEL_UNIT(UNIT_ARTILLERY, 22, 12, 0),
	LEVEL_UNIT(UNIT_ARTILLERY, 14, 11, 0),

	LEVEL_UNIT(UNIT_INFANTRY, 23, 21, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 11, 18, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 16, 22, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 15, 14, 0),

	LEVEL_UNIT(UNIT_COMMAND,     11, 12, 0),
	LEVEL_UNIT(UNIT_COMMAND,     12, 13, 0),
	LEVEL_UNIT(UNIT_COMMAND,     12, 12, 0),
	LEVEL_UNIT(UNIT_COMMAND_END, 13, 12, 0),

	LEVEL_AI_TASK(AIS_IDLE,   0,  0,  0,  0),	// 0
};

// ISLAND
// HOPPERS
static const char level_data_island_hoppers[] = {
	LEVEL_SEED(64048),
	LEVEL_DAYS(34),

	LEVEL_PATCH(10, 26,  2,  7, GTERRAIN_ROAD),
	LEVEL_PATCH( 4, 22,  2,  7, GTERRAIN_ROAD),
	LEVEL_PATCH( 4, 15,  3,  7, GTERRAIN_ROAD),
	LEVEL_PATCH( 5, 14,  1,  5, GTERRAIN_ROAD),
	LEVEL_PATCH(10, 13,  2,  7, GTERRAIN_ROAD),
	LEVEL_PATCH(16, 30,  1,  5, GTERRAIN_ROAD),
	LEVEL_PATCH_END,

	LEVEL_UNIT(UNIT_SCOUT_DRONE, 20, 30, 0),
	LEVEL_UNIT(UNIT_BOMBER,      19, 30, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,   16, 30, 0),

	LEVEL_UNIT(UNIT_HEAVY_TANK,  21, 28, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  21, 29, 0),

	LEVEL_UNIT(UNIT_LIGHT_TANK, 15, 28, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 16, 29, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 22, 29, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 22, 30, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 20, 29, 0),

	LEVEL_UNIT(UNIT_ARTILLERY, 20, 20, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 17, 18, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 25, 18, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 22, 23, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 19, 10, 0),

	LEVEL_UNIT(UNIT_HOVERCRAFT, 26, 15, 1),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 27, 15, 1),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 26, 16, 1),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 27, 16, 1),

	LEVEL_UNIT(UNIT_HOVERCRAFT, 26, 14, 5),

	LEVEL_UNIT(UNIT_HEAVY_TANK,   9, 26, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,   8, 26, 0),

	LEVEL_UNIT(UNIT_INFANTRY, 16, 14, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 22, 14, 0),
	
	LEVEL_UNIT(UNIT_HEAVY_TANK,  20, 16, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  19, 15, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  18, 17, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 20,  8, 0),


	LEVEL_AI_TASK(AIS_IDLE,   0,  0,  0,  0),	// 0
	LEVEL_AI_TASK(AIS_STROLL, 2, 29, 21,  0),	// 1 -> 2
	LEVEL_AI_TASK(AIS_STROLL, 0, 22, 30,  0),	// 2 -> 0

	LEVEL_AI_TASK(AIS_IDLE,   4,  0,  0, 24),	// 3 -> 4
	LEVEL_AI_TASK(AIS_STROLL, 0, 15, 29,  0),	// 4 -> 2

	LEVEL_AI_TASK(AIS_IDLE,   1,  0,  0, 12),	// 5 -> 1
};

// ROLLING
// THUNDER
static const char level_data_rolling_thunder[] = {
	LEVEL_SEED(58381),
	LEVEL_DAYS(24),

	LEVEL_PATCH(17, 11,  1,  8, GTERRAIN_ROAD),
	LEVEL_PATCH( 9, 16,  1,  9, GTERRAIN_ROAD),
	LEVEL_PATCH(22, 14,  0,  5, GTERRAIN_ROAD),
	LEVEL_PATCH(19, 15,  1,  2, GTERRAIN_ROAD),
	LEVEL_PATCH(19, 18,  0,  3, GTERRAIN_ROAD),
	LEVEL_PATCH(14, 21,  1,  5, GTERRAIN_ROAD),

	LEVEL_PATCH_END,

	LEVEL_UNIT(UNIT_BOMBER,      24,  5, 0),
	LEVEL_UNIT(UNIT_BOMBER,      25,  5, 0),
	LEVEL_UNIT(UNIT_BOMBER,      26,  5, 0),

	LEVEL_UNIT(UNIT_ARTILLERY,   24,  4, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,   26,  4, 0),
	LEVEL_UNIT(UNIT_HOVERCRAFT,  26,  2, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 25,  4, 0),

	LEVEL_UNIT(UNIT_ARTILLERY,   16, 21, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,   17, 13, 0),

	LEVEL_UNIT(UNIT_HOVERCRAFT,  28, 23, 1),
	LEVEL_UNIT(UNIT_HOVERCRAFT,  20, 20, 1),
	LEVEL_UNIT(UNIT_HOVERCRAFT,  13, 15, 1),
	LEVEL_UNIT(UNIT_HOVERCRAFT,  12, 12, 1),
	LEVEL_UNIT(UNIT_HOVERCRAFT,  17,  7, 1),

	LEVEL_UNIT(UNIT_HEAVY_TANK,  17, 12, 1),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  22, 14, 1),

	LEVEL_UNIT(UNIT_LIGHT_TANK, 13,  3, 2),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 13,  4, 2),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 26, 16, 2),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 24, 16, 2),

	LEVEL_UNIT(UNIT_AIR_DEFENCE,  5, 22, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE,  7, 28, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE,  5, 24, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE,  3, 21, 0),


	LEVEL_UNIT(UNIT_COMMAND_END,  4, 27, 0),

	LEVEL_AI_TASK(AIS_IDLE,   0,  0,  0,  0),	// 0
	LEVEL_AI_TASK(AIS_STROLL, 0, 25,  5,  0),	// 1 -> 0
	LEVEL_AI_TASK(AIS_STROLL, 1, 24,  9,  0),	// 2 -> 1
};

// VALLEY
// OF DOOM
static const char level_data_valley_of_doom[] = {
	LEVEL_SEED(3585),
	LEVEL_DAYS(24),

	LEVEL_PATCH(  2, 15,  6,  3, GTERRAIN_ROAD),
	LEVEL_PATCH( 21,  6,  6,  3, GTERRAIN_FORREST),
	LEVEL_PATCH( 21,  3,  6,  2, GTERRAIN_BEACH),
	LEVEL_PATCH( 21 , 1,  6,  2, GTERRAIN_BEACH),

	LEVEL_PATCH(  5, 14,  2,  3, GTERRAIN_ROAD),
	LEVEL_PATCH(  8, 16,  1,  3, GTERRAIN_ROAD),
	LEVEL_PATCH( 11, 14,  2, 12, GTERRAIN_ROAD),
	LEVEL_PATCH( 23, 19,  0,  9, GTERRAIN_ROAD),
	LEVEL_PATCH( 22, 11,  5,  1, GTERRAIN_ROAD),
	LEVEL_PATCH( 21, 10,  0, 11, GTERRAIN_ROAD),

	LEVEL_PATCH_END,

	LEVEL_UNIT(UNIT_CHOPPER,  1, 10, 0),
	LEVEL_UNIT(UNIT_CHOPPER,  2, 10, 0),
	LEVEL_UNIT(UNIT_CHOPPER,  2, 11, 0),

	LEVEL_UNIT(UNIT_LIGHT_TANK,  4, 14, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK,  5, 14, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK,  4, 15, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK,  5, 15, 0),

	LEVEL_UNIT(UNIT_HEAVY_TANK,   2, 14, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,   3, 14, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,   3, 15, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,   2, 16, 0),

	LEVEL_UNIT(UNIT_COMMAND_END,  2, 15, 0),

	LEVEL_UNIT(UNIT_LIGHT_TANK, 14, 11, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 10, 18, 0),

	LEVEL_UNIT(UNIT_INFANTRY, 10, 17, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 20,  8, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 20, 20, 0),

	LEVEL_UNIT(UNIT_SCOUT_DRONE, 21,  2, 0),

	LEVEL_UNIT(UNIT_AIR_DEFENCE, 11, 14, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  10, 14, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  10, 15, 0),

	LEVEL_UNIT(UNIT_AIR_DEFENCE, 23, 16, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  21, 19, 0),

	LEVEL_UNIT(UNIT_AIR_DEFENCE, 16,  2, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 19,  4, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 23,  3, 0),
	LEVEL_UNIT(UNIT_AIR_DEFENCE, 22,  1, 0),

	LEVEL_UNIT(UNIT_ARTILLERY,   11,  9, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,   13, 21, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,   29, 12, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,   17, 10, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 21,  1, 0),

	LEVEL_AI_TASK(AIS_IDLE,    0,  0,  0,  0),	// 0
	LEVEL_AI_TASK(AIS_IDLE,    2,  0,  0, 10),	// 1 -> 2
	LEVEL_AI_TASK(AIS_STROLL,  3,  7, 17,  0),	// 2 -> 3
	LEVEL_AI_TASK(AIS_STROLL,  0,  1, 14,  0),	// 3 -> 0
};


// RIVER
// BOAT
static const char level_data_river_boat[] = {
	LEVEL_SEED(24242),
	LEVEL_DAYS(30),

	LEVEL_PATCH( 11, 21,  6,  2, GTERRAIN_BEACH),
	LEVEL_PATCH( 10, 20,  6,  2, GTERRAIN_FORREST),

	LEVEL_PATCH_END,

	LEVEL_UNIT(UNIT_HOVERCRAFT, 1,  2, 0),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 2,  3, 0),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 2,  4, 0),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 2,  5, 0),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 1,  5, 0),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 0,  6, 0),

	LEVEL_UNIT(UNIT_COMMAND_END,  0,  4, 0),

	LEVEL_UNIT(UNIT_SCOUT_DRONE, 1, 12, 2),
	LEVEL_UNIT(UNIT_SCOUT_DRONE, 4, 15, 2),
	LEVEL_UNIT(UNIT_SCOUT_DRONE, 9,  8, 2),

	LEVEL_UNIT(UNIT_CHOPPER, 5, 21, 1),
	LEVEL_UNIT(UNIT_CHOPPER, 6, 24, 1),
	LEVEL_UNIT(UNIT_CHOPPER, 4, 24, 1),

	LEVEL_UNIT(UNIT_CHOPPER, 25, 10, 7),
	LEVEL_UNIT(UNIT_CHOPPER, 25, 11, 7),
	LEVEL_UNIT(UNIT_CHOPPER, 25, 12, 7),

	LEVEL_UNIT(UNIT_HOVERCRAFT, 18, 30, 3),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 19, 30, 3),
	LEVEL_UNIT(UNIT_HOVERCRAFT, 20, 30, 3),

	LEVEL_UNIT(UNIT_CHOPPER,  5, 27, 5),
	LEVEL_UNIT(UNIT_CHOPPER,  5, 28, 5),
	LEVEL_UNIT(UNIT_CHOPPER,  5, 29, 5),

	LEVEL_UNIT(UNIT_HEAVY_TANK,  2, 27, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  3, 27, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  4, 29, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  4, 30, 0),

	LEVEL_UNIT(UNIT_COMMAND_END,  2, 29, 0),

	LEVEL_AI_TASK(AIS_IDLE,    0,  0,  0,  0),	// 0

	LEVEL_AI_TASK(AIS_IDLE,    2,  0,  0, 28),	// 1 -> 2
	LEVEL_AI_TASK(AIS_STROLL,  0,  1,  7,  0),	// 2 -> 0

	LEVEL_AI_TASK(AIS_IDLE,    4,  0,  0, 20),	// 3 -> 4
	LEVEL_AI_TASK(AIS_STROLL,  2, 20, 14,  0),	// 4 -> 2

	LEVEL_AI_TASK(AIS_IDLE,    6,  0,  0, 12),	// 5 -> 6
	LEVEL_AI_TASK(AIS_STROLL,  4, 18, 26,  0),	// 6 -> 4

	LEVEL_AI_TASK(AIS_IDLE,    2,  0,  0, 24),	// 7 -> 2
};

// ESCAPE A
// SIEGE
static const char level_data_escape_a_siege[] = {
	LEVEL_SEED(50126),
	LEVEL_DAYS(15),

	LEVEL_PATCH( 10, 11,  6,  4, GTERRAIN_MOUNTAIN),
	LEVEL_PATCH( 10, 11,  6,  3, GTERRAIN_ROAD),
	LEVEL_PATCH( 23, 14,  2,  3, GTERRAIN_BEACH),

	LEVEL_PATCH_END,

	LEVEL_UNIT(UNIT_INFANTRY, 10, 10, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 11, 10, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 11, 11, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 10, 12, 0),
	LEVEL_UNIT(UNIT_INFANTRY,  9, 11, 0),
	LEVEL_UNIT(UNIT_INFANTRY,  9, 10, 0),

	LEVEL_UNIT(UNIT_INFANTRY, 12, 10, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 12, 12, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 10, 13, 0),
	LEVEL_UNIT(UNIT_INFANTRY,  8, 12, 0),
	LEVEL_UNIT(UNIT_INFANTRY,  8, 10, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 10,  9, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 10, 11, 0),

	LEVEL_UNIT(UNIT_HEAVY_TANK,  6, 10, 1),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  9,  7, 1),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 13,  8, 1),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 14, 12, 1),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 13, 13, 1),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 11, 15, 1),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  8, 15, 1),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  7, 13, 1),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  5, 12, 1),

	LEVEL_UNIT(UNIT_ARTILLERY,   26,  5, 2),
	LEVEL_UNIT(UNIT_ARTILLERY,   25, 17, 2),
	LEVEL_UNIT(UNIT_ARTILLERY,    0, 19, 4),
	LEVEL_UNIT(UNIT_ARTILLERY,    0, 24, 4),

	LEVEL_UNIT(UNIT_COMMAND_END, 27,  1, 0),

	LEVEL_AI_TASK(AIS_IDLE,    0,  0,  0,  0),	// 0
	LEVEL_AI_TASK(AIS_STROLL,  1, 10, 11,  0),	// 1 -> 1

	LEVEL_AI_TASK(AIS_RUSH,  3, 23, 11,  0),	// 2 -> 3
	LEVEL_AI_TASK(AIS_RUSH,  0, 15, 14,  0),	// 3 -> 0

	LEVEL_AI_TASK(AIS_RUSH,  5,  7, 22,  0),	// 4 -> 5
	LEVEL_AI_TASK(AIS_RUSH,  0, 10, 20,  0),	// 5 -> 0
};

// BAIT AND
// SWITCH
static const char level_data_bait_and_switch[] = {
	LEVEL_SEED(23154),
	LEVEL_DAYS(24),

	LEVEL_PATCH( 19,  8,  1,  2, GTERRAIN_SEA),
	LEVEL_PATCH( 14, 13,  6,  2, GTERRAIN_BEACH),
	LEVEL_PATCH(  8, 18,  6,  2, GTERRAIN_BEACH),
	LEVEL_PATCH( 16, 15,  6,  1, GTERRAIN_BEACH),
	LEVEL_PATCH( 12, 20,  2,  2, GTERRAIN_BEACH),
	LEVEL_PATCH( 14, 20,  6,  1, GTERRAIN_BEACH),

	LEVEL_PATCH_END,

	LEVEL_UNIT(UNIT_INFANTRY, 12, 16, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 13, 15, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 11, 16, 0),
	LEVEL_UNIT(UNIT_INFANTRY, 12, 17, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 19, 4, 0),

	LEVEL_UNIT(UNIT_HEAVY_TANK, 15, 19, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 16, 19, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 16, 20, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 17, 19, 0),

	LEVEL_UNIT(UNIT_COMMAND_END, 17, 26, 0),

	LEVEL_AI_TASK(AIS_IDLE,    0,  0,  0,  0),	// 0
};

// LIGHT
// BRIGADE
static const char level_data_light_brigade[] = {
	LEVEL_SEED(17971),
	LEVEL_DAYS(30),

	LEVEL_PATCH( 28, 30,  5,  9, GTERRAIN_ROAD),
	LEVEL_PATCH( 20, 25,  5,  4, GTERRAIN_ROAD),
	LEVEL_PATCH( 17, 18,  3,  5, GTERRAIN_ROAD),
	LEVEL_PATCH(  7,  1,  6,  2, GTERRAIN_MOUNTAIN),

	LEVEL_PATCH_END,

	LEVEL_UNIT(UNIT_LIGHT_TANK, 26, 28, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 26, 29, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 26, 30, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 27, 27, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 27, 28, 0),
	LEVEL_UNIT(UNIT_LIGHT_TANK, 27, 29, 0),

	LEVEL_UNIT(UNIT_ARTILLERY,   27, 30, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,   28, 29, 0),
	LEVEL_UNIT(UNIT_COMMAND_END, 28, 30, 0),

	LEVEL_UNIT(UNIT_HEAVY_TANK, 15, 22, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK, 19, 18, 0),

	LEVEL_UNIT(UNIT_HEAVY_TANK, 11, 13, 0),
	LEVEL_UNIT(UNIT_HEAVY_TANK,  8, 12, 0),

	LEVEL_UNIT(UNIT_ARTILLERY,   23,  5, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,   23,  6, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,   24, 15, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,   24, 16, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,    7, 16, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,    7, 17, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,    8, 25, 0),
	LEVEL_UNIT(UNIT_ARTILLERY,    8, 26, 0),

	LEVEL_UNIT(UNIT_COMMAND_END,  7, 1, 0),

	LEVEL_AI_TASK(AIS_IDLE,    0,  0,  0,  0),	// 0
};

const LevelInfo	LevelInfos[NUM_LEVELS] =
{
	{
		"OVERTURE\n", 
		level_data_overture,
		"OVERTURE",
		TUNE_INIT
	},
	{
		"ROAD TO\nVICTORY", 
		level_data_road_to_victory,
		"ABSTRACT",
		TUNE_INIT
	},
	{
		"FIRE AND\nRETREAT", 
		level_data_fire_and_retreat,
		"TWIZZLED",
		TUNE_INIT
	},
	{
		"MOUNTAIN\nFORTRESS", 
		level_data_mountain_fortress,
		"PICKWICK",
		TUNE_INIT_JONNY
	},
	{
		"VALKIRYE\nRIDE", 
		level_data_valkyrie_ride,
		"LUNCHBOX",
		TUNE_INIT_TOPGUN
	},
	{
		"SPECIAL\nFORCES", 
		level_data_special_forces,
		"JUMPSUIT",
		TUNE_INIT
	},
	{
		"ISLAND\nHOPPERS", 
		level_data_island_hoppers,
		"BACKLINK",
		TUNE_INIT
	},
	{
		"ROLLING\nTHUNDER", 
		level_data_rolling_thunder,
		"BLUEJAYS",
		TUNE_INIT_TOPGUN
	},
	{
		"VALLEY\nOF DOOM", 
		level_data_valley_of_doom,
		"MOBILIZE",
		TUNE_INIT_JONNY
	},
	{
		"RIVER\nBOAT", 
		level_data_river_boat,
		"ARQUEBUS",
		TUNE_INIT_BRITTANIA
	},
	{
		"ESCAPE A\nSIEGE", 
		level_data_escape_a_siege,
		"MORIBUND",
		TUNE_INIT_JONNY
	},
	{
		"BAIT AND\nSWITCH", 
		level_data_bait_and_switch,
		"MORPHEUS",
		TUNE_INIT
	},
	{
		"LIGHT\nBRIGADE", 
		level_data_light_brigade,
		"BALACLAV",
		TUNE_INIT_BRITTANIA
	},
};

bool LevelUnlocked[NUM_LEVELS] = {
	true, false, false, false, false,
	false, false, false, false, false,
	false
};

void level_complete_setup(void)
{
	grid_blank();
	grid_init_sprite();

	drawBaseGrid();

	char	ci = unit_find(UNIT_COMMAND | UNIT_TEAM_1);

	cursor_init(units[ci].mx, units[ci].my);

	drawUnits();
	resetFlags();
	calcVisibility(UNIT_TEAM_1);
	calcThreatened(UNIT_TEAM_2);

	updateColors();
}

void level_restart(char level)
{	
	grid_blank();

	drawBaseGrid();
	status_init();

	level_setup_cmd(LevelInfos[level].data, false);

	for(char y=0; y<32; y++)
	{
		for(char x=0; x<32; x++)
		{
			gridstate[y][x] &= GS_TERRAIN;
		}
	}

	level_complete_setup();
}

void level_setup(char level)
{	
	grid_blank();

	music_patch_voice3(true);

	music_init(LevelInfos[level].tune);

	drawBaseGrid();
	status_init();

	tovl_show(LevelInfos[level].name, VCOL_YELLOW);


	level_setup_cmd(LevelInfos[level].data, true);

	tovl_hide();

	level_complete_setup();

	tovl_wait();
}
